name: "Create Conan Package"
on: push

jobs:
  build_linux_x86_64:
    name: "Linux"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      name: "x86_64"
      image: "ubuntu-22.04"
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan
      conan_deploy_artifacts: true

  build_windows_x86_64:
    name: "Windows"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      name: "x86_64"
      image: "windows-2022"
      conan_host_profile_path: "hostProfiles/windowsMinGW.profile"
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan
      conan_deploy_artifacts: true

  build_macos_armv8:
    name: "Macos"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      name: "armv8"
      image: "macos-15"
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan
      conan_deploy_artifacts: true
