name: "Create Conan Package"
on: push

jobs:
  build_linux_x86_64:
    name: "Linux"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      name: "x86_64"
      image: "ubuntu-22.04"
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan

  build_linux_armv8:
    name: "Linux"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      name: "armv8"
      image: "ubuntu-22.04-arm"
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan

  build_windows_x86_64:
    name: "Windows"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      name: "x86_64"
      image: "windows-2022"
      conan_host_profile: "windowsMinGW"
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan

  build_macos_x86_64:
    name: "Macos"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      name: "x86_64"
      image: "macos-13"
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan

  build_macos_armv8:
    name: "Macos"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      name: "armv8"
      image: "macos-14"
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan
